# Generated by Django 4.2 on 2023-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD7Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('answer5', models.IntegerField()),
                ('answer6', models.IntegerField()),
                ('answer7', models.IntegerField()),
                ('userId', models.CharField(max_length=30)),
                ('Overallscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PHQ9Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('answer5', models.IntegerField()),
                ('answer6', models.IntegerField()),
                ('answer7', models.IntegerField()),
                ('answer8', models.IntegerField()),
                ('answer9', models.IntegerField()),
                ('userId', models.CharField(max_length=30)),
                ('Overallscore', models.IntegerField()),
            ],
        ),
    ]
