# Generated by Django 4.2 on 2023-04-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_gad7form_phq9form'),
    ]

    operations = [
        migrations.AddField(
            model_name='gad7form',
            name='date',
            field=models.IntegerField(default=1682811478594),
        ),
        migrations.AddField(
            model_name='phq9form',
            name='date',
            field=models.IntegerField(default=1682811478594),
        ),
    ]
